import { HttpStatusCode } from './types';

export const HTTP_STATUS_CODES: HttpStatusCode[] = [
    // ─── 1xx Informational ────────────────────────────────────────────────────
    {
        code: 100,
        name: 'Continue',
        description: 'The server has received the request headers and the client should proceed to send the request body.',
        longDescription: 'The 100 Continue status indicates that the server has received the initial part of the request (headers) and the client should continue sending the request body. This is useful for large uploads where the client wants to check if the server will accept the request before transmitting a large payload. If the server rejects the headers (e.g. due to authentication failure), the client avoids wasting bandwidth.',
        class: '1xx',
        category: 'Informational',
        spec: 'RFC 9110',
        useCase: 'Client sends large file upload with "Expect: 100-continue" header before transmitting the body.',
    },
    {
        code: 101,
        name: 'Switching Protocols',
        description: 'Server agrees to switch protocols as requested by the client.',
        longDescription: 'The 101 Switching Protocols response indicates that the server understands and is willing to comply with the client\'s request, via the Upgrade header field, to switch protocols. The server sends this response before the empty line that terminates the 101 response. This is commonly used when upgrading from HTTP to WebSocket connections.',
        class: '1xx',
        category: 'Informational',
        spec: 'RFC 9110',
        useCase: 'Browser requests protocol upgrade from HTTP/1.1 to WebSocket for real-time bi-directional communication.',
    },
    {
        code: 102,
        name: 'Processing',
        description: 'Server has received and is processing the request, but no response is available yet.',
        longDescription: 'The 102 Processing status (WebDAV) is an interim response that indicates the server has received and is processing the request, but does not yet have a final response. It prevents the client from timing out assuming the request was lost. This is particularly useful for long-running WebDAV operations.',
        class: '1xx',
        category: 'Informational',
        spec: 'RFC 2518 (WebDAV)',
        useCase: 'WebDAV client performing a long-running MOVE or COPY operation on a large directory structure.',
    },
    {
        code: 103,
        name: 'Early Hints',
        description: 'Primarily intended for use with the Link header, letting the user agent preload resources.',
        longDescription: 'The 103 Early Hints status code is used to return some response headers before final HTTP message. It allows servers to send hints to clients about what resources should be preloaded before the final response is ready. This can significantly improve page load performance by allowing browsers to start loading critical assets such as CSS or JavaScript while the server is still processing the main response.',
        class: '1xx',
        category: 'Informational',
        spec: 'RFC 8297',
        useCase: 'Server sends early hints to preload critical CSS and fonts while generating a dynamic HTML page.',
    },

    // ─── 2xx Success ──────────────────────────────────────────────────────────
    {
        code: 200,
        name: 'OK',
        description: 'Standard response for successful HTTP requests.',
        longDescription: 'The 200 OK status is the most common HTTP response code indicating that the request has succeeded. The meaning of the success depends on the HTTP method: GET returns the requested resource, HEAD returns headers without a body, POST returns a description of the result, PUT/DELETE/OPTIONS/TRACE return results of the action. The response body contains the requested resource or the result of the action.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 9110',
        useCase: 'REST API returns data for a successful GET /users/123 request.',
    },
    {
        code: 201,
        name: 'Created',
        description: 'The request has been fulfilled, resulting in the creation of a new resource.',
        longDescription: 'The 201 Created status indicates that the request has been fulfilled and has resulted in one or more new resources being created. The newly created resource can be referenced by the URI(s) returned in the entity of the response, with the most specific URI for the resource given by a Location header field. The response should include a representation of the created resource.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 9110',
        useCase: 'POST /users creates a new user and returns 201 with a Location header pointing to /users/456.',
    },
    {
        code: 202,
        name: 'Accepted',
        description: 'Request has been accepted but not yet completed.',
        longDescription: 'The 202 Accepted status indicates the request has been accepted for processing, but the processing has not been completed. The request might or might not be eventually acted upon, as it may be disallowed when processing actually takes place. It is intended for cases where another process or server handles the request, or for batch processing. The response should include an indication of the request\'s current status and a pointer to a status monitor.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 9110',
        useCase: 'Submitting a video transcoding job that will be processed asynchronously in a background queue.',
    },
    {
        code: 203,
        name: 'Non-Authoritative Information',
        description: 'Request was successful but the enclosed payload was modified by a proxy.',
        longDescription: 'The 203 Non-Authoritative Information response indicates a successful request, but the enclosed payload has been modified by a transforming proxy from the 200 response of the origin server. The proxy may be providing cached or transformed content. This status allows a proxy to communicate that the response has been modified, distinguishing it from an unmodified 200 response.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 9110',
        useCase: 'A caching proxy returns a modified version of the response with additional metadata headers stripped.',
    },
    {
        code: 204,
        name: 'No Content',
        description: 'Server successfully processed the request, not returning any content.',
        longDescription: 'The 204 No Content status indicates the server successfully processed the request but is not returning any content. This is commonly used for DELETE requests, PUT updates, or actions where a response body is unnecessary. The response should not contain a message body, and must never include a Content-Length or Transfer-Encoding header. It is useful when the client doesn\'t need to refresh the page.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 9110',
        useCase: 'DELETE /users/123 returns 204 confirming deletion without a response body.',
    },
    {
        code: 205,
        name: 'Reset Content',
        description: 'Server successfully processed the request, asks client to reset the document view.',
        longDescription: 'The 205 Reset Content status tells the client to reset the document which sent this request. The response should not include a response body. It is similar to 204 No Content but additionally requires the requester to reset the document view, such as clearing form inputs after a successful form submission, so the user can input more data.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 9110',
        useCase: 'After submitting a feedback form, the server returns 205 so the browser clears the form fields for a new entry.',
    },
    {
        code: 206,
        name: 'Partial Content',
        description: 'Server is delivering only part of the resource (byte serving).',
        longDescription: 'The 206 Partial Content status is used when the server is fulfilling a partial GET request for the resource. The request must have included a Range header indicating the desired range. This enables resumable downloads, video streaming, and parallel downloading of large files by allowing clients to request specific byte ranges of a resource.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 9110',
        useCase: 'Video player requests bytes 0–1048575 of a video file for streaming the first segment.',
    },
    {
        code: 207,
        name: 'Multi-Status',
        description: 'Multiple status codes might be appropriate.',
        longDescription: 'The 207 Multi-Status response (WebDAV) conveys information about multiple resources in situations where multiple status codes might be appropriate. The body of a 207 Multi-Status response is an XML message containing separate responses for each resource. This is used in WebDAV operations that affect multiple resources simultaneously, such as a PROPFIND on a collection.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 4918 (WebDAV)',
        useCase: 'WebDAV PROPFIND on a folder returns properties and individual status for each contained resource.',
    },
    {
        code: 208,
        name: 'Already Reported',
        description: 'Members of a DAV binding have already been enumerated in a preceding part of the response.',
        longDescription: 'The 208 Already Reported status (WebDAV) is used inside a DAV: propstat response element to avoid enumerating the internal members of multiple bindings to the same collection repeatedly. It avoids infinite loops when a resource is bound to multiple locations in a WebDAV hierarchy. The server uses this to indicate that a resource was already listed in an earlier part of the multi-status response.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 5842 (WebDAV)',
        useCase: 'WebDAV PROPFIND discovers a resource that was already returned earlier in the same multi-status response.',
    },
    {
        code: 226,
        name: 'IM Used',
        description: 'Server has fulfilled a request for the resource using instance manipulations.',
        longDescription: 'The 226 IM Used status indicates the server has fulfilled a GET request for the resource, and the response is a representation of one or more instance-manipulations applied to the current instance. This is part of HTTP Delta Encoding (RFC 3229), where the server returns a delta encoding rather than the full resource, reducing bandwidth when only a portion of the resource has changed.',
        class: '2xx',
        category: 'Success',
        spec: 'RFC 3229',
        useCase: 'Client requests a delta update of a large document; server returns only the changes since the last known version.',
    },

    // ─── 3xx Redirection ──────────────────────────────────────────────────────
    {
        code: 300,
        name: 'Multiple Choices',
        description: 'Indicates multiple options for the resource from which the client may choose.',
        longDescription: 'The 300 Multiple Choices status indicates that the target resource has more than one representation. The server can provide information about the alternatives so the user or user agent can select a preferred representation and redirect its request to that location. If the server has a preferred choice, it should indicate that with a Location header. This is rarely used in practice.',
        class: '3xx',
        category: 'Redirection',
        spec: 'RFC 9110',
        useCase: 'A resource is available in multiple languages; the server offers links to each localized version.',
    },
    {
        code: 301,
        name: 'Moved Permanently',
        description: 'This and all future requests should be directed to the given URI.',
        longDescription: 'The 301 Moved Permanently status indicates that the requested resource has been permanently moved to the URL given by the Location response header. A browser redirects to this new URL, and search engines update their links. The original URL should be considered obsolete and replaced by the Location URL for all future requests. Search engines pass most link equity to the new URL.',
        class: '3xx',
        category: 'Redirection',
        spec: 'RFC 9110',
        useCase: 'Website domain migration from http://old-domain.com to https://new-domain.com with 301 to preserve SEO rankings.',
    },
    {
        code: 302,
        name: 'Found',
        description: 'Resource temporarily resides under a different URI.',
        longDescription: 'The 302 Found status indicates that the resource requested has been temporarily moved to the URL given by the Location header. A browser redirects to this URL but the original URL should be used for future requests since the redirect is temporary. Unlike 301, this does not cause search engines to update their links. Note: many clients incorrectly change POST to GET when following a 302 redirect.',
        class: '3xx',
        category: 'Redirection',
        spec: 'RFC 9110',
        useCase: 'Redirecting a user to a login page when they try to access a protected resource that requires authentication.',
    },
    {
        code: 303,
        name: 'See Other',
        description: 'Response to the request can be found under another URI using GET method.',
        longDescription: 'The 303 See Other status indicates that the server is redirecting the user agent to a different resource, as indicated by a URI in the Location header field. This is used to redirect after a POST (or PUT/DELETE) so the client performs a GET on the redirect target, preventing form resubmission on page refresh. It is the correct way to implement the Post/Redirect/Get (PRG) pattern.',
        class: '3xx',
        category: 'Redirection',
        spec: 'RFC 9110',
        useCase: 'After a POST form submission creates a resource, server returns 303 redirecting to a confirmation page.',
    },
    {
        code: 304,
        name: 'Not Modified',
        description: 'Resource has not been modified since last requested.',
        longDescription: 'The 304 Not Modified response indicates a conditional GET or HEAD request received a 304 response, meaning the client\'s cached version of the resource is still current and the browser should use its cached copy. The response must not contain a message body. It saves bandwidth by avoiding re-sending the full response when the content hasn\'t changed, using ETags or Last-Modified headers for validation.',
        class: '3xx',
        category: 'Redirection',
        spec: 'RFC 9110',
        useCase: 'Browser sends If-None-Match with cached ETag; server returns 304 so browser uses its cached copy of a CSS file.',
    },
    {
        code: 305,
        name: 'Use Proxy',
        description: 'Resource must be accessed through the proxy given by the Location field.',
        longDescription: 'The 305 Use Proxy status (deprecated) was used to indicate that the requested resource must be accessed through the proxy given by the Location field. It has been deprecated due to security concerns — it could be used to redirect clients to malicious proxies. Many clients ignore this status or treat it as an error. It should not be used in modern applications.',
        class: '3xx',
        category: 'Redirection',
        isDeprecated: true,
        spec: 'RFC 9110 (deprecated)',
        useCase: 'Historically used to force clients through a corporate proxy — now deprecated due to security risks.',
    },
    {
        code: 307,
        name: 'Temporary Redirect',
        description: 'Resource is temporarily at a different URI; request method should not change.',
        longDescription: 'The 307 Temporary Redirect status indicates the requested resource has been temporarily moved to another URI, specified in the Location header. Unlike 302, the HTTP method (POST, PUT, etc.) must not be changed when following the redirect — the same method must be used again. This makes 307 the correct redirect code when you need to preserve the original request method.',
        class: '3xx',
        category: 'Redirection',
        spec: 'RFC 9110',
        useCase: 'API endpoint temporarily moved for maintenance; POST requests must be resubmitted to the new URL unchanged.',
    },
    {
        code: 308,
        name: 'Permanent Redirect',
        description: 'Resource is permanently at a different URI; request method should not change.',
        longDescription: 'The 308 Permanent Redirect status indicates the requested resource has been permanently moved to the URI given by the Location header. Like 307 (but permanent), the HTTP method must not change when following the redirect. Future requests should use the new URL. It combines the permanence of 301 with the method-preservation guarantee of 307, making it ideal for permanent API endpoint migrations.',
        class: '3xx',
        category: 'Redirection',
        spec: 'RFC 9110',
        useCase: 'Permanent API restructuring from POST /v1/items to POST /v2/items while preserving the POST method.',
    },

    // ─── 4xx Client Errors ────────────────────────────────────────────────────
    {
        code: 400,
        name: 'Bad Request',
        description: 'Server cannot process the request due to client error.',
        longDescription: 'The 400 Bad Request status indicates the server cannot or will not process the request due to something that is perceived to be a client error, such as malformed request syntax, invalid request message framing, or deceptive request routing. The client should not repeat this request without modification. This is a generic error for any client-side issue that doesn\'t fit a more specific 4xx code.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'API receives JSON with a missing required field or malformed syntax, returning 400 with validation error details.',
    },
    {
        code: 401,
        name: 'Unauthorized',
        description: 'Authentication is required and has failed or not been provided.',
        longDescription: 'The 401 Unauthorized status (despite the name, it means unauthenticated) indicates that the request has not been applied because it lacks valid authentication credentials for the target resource. The server must send a WWW-Authenticate header to inform the client which authentication scheme to use. The client may repeat the request with suitable credentials.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'API request made without a Bearer token; server returns 401 with WWW-Authenticate header indicating the required scheme.',
    },
    {
        code: 402,
        name: 'Payment Required',
        description: 'Reserved for future use; some services use it for billing or rate limiting.',
        longDescription: 'The 402 Payment Required status was originally intended for digital payment systems and digital cash schemes, but it is not used for that purpose and remains reserved. Some APIs use it to indicate that the user\'s subscription has expired or they need to pay to access a feature. There is no standard use case, and implementations vary widely across different services.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'A SaaS API returns 402 when a free-tier user exceeds their monthly API quota or accesses a premium feature.',
    },
    {
        code: 403,
        name: 'Forbidden',
        description: 'Server understood request but refuses to authorize it.',
        longDescription: 'The 403 Forbidden status indicates the server understood the request but refuses to authorize it. Unlike 401, re-authenticating will not make a difference — the server is refusing access regardless of credentials. This is typically used when the user is authenticated but lacks the necessary permissions. The server may indicate whether authorization is applicable (as opposed to 404, which hides the existence of a resource).',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Authenticated user attempts to delete another user\'s account; server returns 403 as they lack admin privileges.',
    },
    {
        code: 404,
        name: 'Not Found',
        description: 'The requested resource could not be found on the server.',
        longDescription: 'The 404 Not Found status indicates the server cannot find the requested resource. Links that lead to a 404 page are often called "broken" or "dead" links. A 404 can be temporary or permanent. Sometimes 404 is returned instead of 403 to hide the existence of a resource from unauthorized users. It is the most recognized HTTP error code by end users.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'GET /users/9999 returns 404 because no user with ID 9999 exists in the database.',
    },
    {
        code: 405,
        name: 'Method Not Allowed',
        description: 'Request method not supported for the requested resource.',
        longDescription: 'The 405 Method Not Allowed status indicates that the request method is known by the server but is not supported by the target resource. The response must include an Allow header containing a list of currently supported methods for the target resource. For example, an endpoint that only supports GET and HEAD would return 405 if a DELETE request is made to it.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Sending DELETE to a read-only /status endpoint returns 405 with Allow: GET, HEAD header.',
    },
    {
        code: 406,
        name: 'Not Acceptable',
        description: 'Requested resource only capable of generating content not acceptable by the client.',
        longDescription: 'The 406 Not Acceptable status indicates the server cannot produce a response matching the list of acceptable values defined by the request\'s proactive content negotiation headers (Accept, Accept-Encoding, Accept-Language, etc.), and the server is unwilling to supply a default representation. In practice, this error is very rarely used; servers typically return a default format instead.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Client sends Accept: application/xml but the API only supports JSON responses.',
    },
    {
        code: 407,
        name: 'Proxy Authentication Required',
        description: 'Client must authenticate itself with the proxy.',
        longDescription: 'The 407 Proxy Authentication Required status is similar to 401 Unauthorized, but it indicates that the client needs to authenticate itself with the proxy. The proxy must return a Proxy-Authenticate header containing a challenge applicable to the proxy for the requested resource. The client may repeat the request with a Proxy-Authorization header field.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Corporate proxy requires authentication before forwarding requests to the internet; client must provide proxy credentials.',
    },
    {
        code: 408,
        name: 'Request Timeout',
        description: 'Server timed out waiting for the request.',
        longDescription: 'The 408 Request Timeout status means the server timed out waiting for the request. According to HTTP specifications, the client did not produce a request within the time the server was prepared to wait. Some servers send a 408 response even without the client having sent a request. This is intended to close idle connections and free up server resources.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Client opens a connection but is too slow sending the request headers; server times out after its configured threshold.',
    },
    {
        code: 409,
        name: 'Conflict',
        description: 'Request could not be processed because of conflict in the current state of the resource.',
        longDescription: 'The 409 Conflict status indicates the request could not be processed because of a conflict in the current state of the target resource. Conflicts are most likely to occur in response to a PUT request — for example, a version control conflict when editing a resource, or trying to create a resource with an ID that already exists. The response should include enough information for the user to recognize the source of the conflict.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Attempting to register a username that is already taken returns 409 with a message indicating the conflict.',
    },
    {
        code: 410,
        name: 'Gone',
        description: 'Resource is no longer available and will not be available again.',
        longDescription: 'The 410 Gone status indicates that access to the target resource is no longer available at the origin server and this condition is likely to be permanent. If the origin server does not know, or has no facility to determine, whether or not the condition is permanent, a 404 status code should be used instead. 410 responses are cacheable by default and tell search engines to remove the URL from their index.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'A promotional landing page that has permanently expired returns 410 to signal search engines to de-index the URL.',
    },
    {
        code: 411,
        name: 'Length Required',
        description: 'Request did not specify the length of its content.',
        longDescription: 'The 411 Length Required status indicates the server refuses to accept the request without a defined Content-Length header. The client may repeat the request after adding a valid Content-Length header. This is typically required for POST or PUT requests with a request body when the server needs to know the size of the content ahead of time and does not accept chunked transfer encoding.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'A POST request body sent without Content-Length header to a server that requires it for streaming uploads.',
    },
    {
        code: 412,
        name: 'Precondition Failed',
        description: 'Server does not meet one of the preconditions that the requester put on the request.',
        longDescription: 'The 412 Precondition Failed status indicates one or more conditions given in the request header fields evaluated to false when tested on the server. This allows the client to place preconditions on the current resource state (its current representations and metadata) and to prevent the request method from being applied if the target resource is in an unexpected state. Used with conditional headers like If-Match or If-Unmodified-Since.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Optimistic concurrency control: PUT with If-Match returns 412 if the ETag doesn\'t match, indicating someone else modified the resource.',
    },
    {
        code: 413,
        name: 'Content Too Large',
        description: 'Request entity is larger than limits defined by server.',
        longDescription: 'The 413 Content Too Large (formerly "Payload Too Large") status indicates the server is refusing to process the request because the request payload is larger than the server is willing or able to process. The server may close the connection to prevent the client from continuing the request. If the condition is temporary, the server should send a Retry-After header indicating when to try again.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Uploading a 100 MB image to an endpoint with a 10 MB limit returns 413 Content Too Large.',
    },
    {
        code: 414,
        name: 'URI Too Long',
        description: 'URI provided was too long for the server to process.',
        longDescription: 'The 414 URI Too Long status indicates the server is refusing to service the request because the request-target (URI) is longer than the server is willing to interpret. This can occur when a client converts a POST request with a long query string to a GET request, or when there is a redirection loop. Most web servers have configurable limits on URI length, typically between 2,000 and 8,000 characters.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'A GET request with an excessively long query string containing thousands of filter parameters.',
    },
    {
        code: 415,
        name: 'Unsupported Media Type',
        description: 'Request entity has a media type which the server does not support.',
        longDescription: 'The 415 Unsupported Media Type status indicates the server refuses to accept the request because the payload format specified by the Content-Type or Content-Encoding headers is unsupported. For example, the client sends XML but the server only supports JSON. The server should indicate what media types it does accept, typically in the response body or Accept-Post/Accept-Patch headers.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'POST request with Content-Type: text/plain to an endpoint that only accepts application/json.',
    },
    {
        code: 416,
        name: 'Range Not Satisfiable',
        description: 'Client requested a portion of the file that lies outside the file\'s range.',
        longDescription: 'The 416 Range Not Satisfiable status indicates that none of the ranges in the Range request header field overlap the current extent of the selected resource, or the set of ranges requested has been rejected due to invalid ranges or an excessive number of small or overlapping ranges. The response must include a Content-Range header with the actual size of the resource.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Resuming a download with Range: bytes=5000-9999 on a 3 KB file returns 416 Range Not Satisfiable.',
    },
    {
        code: 417,
        name: 'Expectation Failed',
        description: 'Server cannot meet the requirements of the Expect request-header field.',
        longDescription: 'The 417 Expectation Failed status indicates the expectation given in an Expect request header field could not be met by at least one of the inbound servers. If the request included an Expect: 100-continue header and the server decided not to continue, it responds with 417. This tells the client the server does not support the 100-continue mechanism and the client should not use it for future requests.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Client sends Expect: 100-continue for a large upload to a server that doesn\'t support the 100-continue mechanism.',
    },
    {
        code: 418,
        name: "I'm a Teapot",
        description: "Easter egg: server refuses to brew coffee because it is a teapot (RFC 2324).",
        longDescription: "The 418 I'm a Teapot status is an April Fools' joke defined in RFC 2324, Hyper Text Coffee Pot Control Protocol (HTCPCP/1.0), published on April 1, 1998. The server returns this response when asked to brew coffee with a teapot. It has since been adopted as a permanent HTTP status code and is widely used by developers as a humorous response to indicate that the server refuses to perform the requested action for whimsical reasons.",
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 2324 (April Fools)',
        useCase: "Used humorously in developer Easter eggs or to reject requests that the server humorously 'refuses' to process.",
    },
    {
        code: 421,
        name: 'Misdirected Request',
        description: 'Request was directed at a server that is not able to produce a response.',
        longDescription: 'The 421 Misdirected Request status indicates the request was directed at a server that is not able to produce a response. This can happen if a connection is reused to send a request for a different domain than the original connection was established for. It can also be sent by a server that is not configured to produce responses for the combination of scheme and authority included in the request URI.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'HTTP/2 connection reuse directed to a server that cannot handle the SNI hostname in the request.',
    },
    {
        code: 422,
        name: 'Unprocessable Content',
        description: 'Request was well-formed but could not be followed due to semantic errors.',
        longDescription: 'The 422 Unprocessable Content (formerly "Unprocessable Entity", WebDAV) status indicates the server understands the content type and the request syntax is correct, but it was unable to process the contained instructions due to semantic errors. It is widely used in REST APIs to indicate validation errors — the request is syntactically valid JSON/XML but fails business logic validation rules.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'POST /users with valid JSON but invalid email format or age below minimum returns 422 with field-level validation errors.',
    },
    {
        code: 423,
        name: 'Locked',
        description: 'The resource being accessed is locked.',
        longDescription: 'The 423 Locked status (WebDAV) indicates that the source or destination resource of a method is locked. The response should contain an appropriate precondition or postcondition code, such as "lock-token-submitted" or "no-conflicting-lock". WebDAV servers use this to prevent simultaneous modifications to the same resource by multiple clients.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 4918 (WebDAV)',
        useCase: 'WebDAV client tries to edit a document that another user has exclusively locked for editing.',
    },
    {
        code: 424,
        name: 'Failed Dependency',
        description: 'Request failed because it depended on another request that failed.',
        longDescription: 'The 424 Failed Dependency status (WebDAV) indicates the method could not be performed on the resource because the requested action depended on another action and that action failed. For example, if a PROPPATCH operation changes several properties at once and one fails, all the others will also be reported as 424 Failed Dependency since the operation is atomic.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 4918 (WebDAV)',
        useCase: 'WebDAV PROPPATCH fails on one property, causing all dependent property changes to be rolled back with 424.',
    },
    {
        code: 425,
        name: 'Too Early',
        description: 'Server is unwilling to risk processing a request that might be replayed.',
        longDescription: 'The 425 Too Early status indicates that the server is unwilling to risk processing a request that might be replayed. When a TLS 1.3 early data (0-RTT) request is received, the server may return 425 if it cannot determine whether the request is a replay of a previous request. Clients receiving this status should not retry the request with early data; they should wait for the handshake to complete.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 8470',
        useCase: 'TLS 1.3 early data (0-RTT) request is rejected because the server cannot verify it is not a replay attack.',
    },
    {
        code: 426,
        name: 'Upgrade Required',
        description: 'Client should switch to a different protocol.',
        longDescription: 'The 426 Upgrade Required status indicates the server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol. The server must send an Upgrade header in a 426 response to indicate the required protocol(s). A common use case is requiring clients to switch from HTTP/1.1 to HTTP/2 or to use HTTPS instead of HTTP.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 9110',
        useCase: 'Server requires TLS connection; returns 426 with Upgrade: TLS/1.3 header to plain HTTP request.',
    },
    {
        code: 428,
        name: 'Precondition Required',
        description: 'Origin server requires the request to be conditional.',
        longDescription: 'The 428 Precondition Required status indicates the origin server requires the request to be conditional. The purpose of this is to prevent the "lost update" problem, where a client GETs a resource\'s state, modifies it, and PUTs it back while another client modifies the resource in the meantime. By requiring conditional requests (If-Match headers), the server ensures changes are applied only to the intended version.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 6585',
        useCase: 'Server requires If-Match header on PUT requests to prevent concurrent modification conflicts.',
    },
    {
        code: 429,
        name: 'Too Many Requests',
        description: 'User has sent too many requests in a given amount of time (rate limiting).',
        longDescription: 'The 429 Too Many Requests status indicates the user has sent too many requests in a given amount of time. The server may include a Retry-After header indicating how long to wait before making a new request. This is used for rate limiting API access to prevent abuse and ensure fair resource usage among clients. Many APIs combine this with X-RateLimit-Limit and X-RateLimit-Remaining headers.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 6585',
        useCase: 'Public API returns 429 after 100 requests per minute are exceeded, with Retry-After: 60 indicating when to retry.',
    },
    {
        code: 431,
        name: 'Request Header Fields Too Large',
        description: 'Individual header field or all header fields collectively are too large.',
        longDescription: 'The 431 Request Header Fields Too Large status indicates the server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large. The server may indicate which header field is too large, or simply that the total header section is too large. Clients can reduce the size of the request by clearing cookies, reducing overly large headers, or re-authenticating.',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 6585',
        useCase: 'Browser sends a request with accumulated cookies totaling over 8 KB, exceeding the server\'s header size limit.',
    },
    {
        code: 451,
        name: 'Unavailable For Legal Reasons',
        description: 'Resource unavailable for legal reasons such as government-mandated censorship.',
        longDescription: 'The 451 Unavailable For Legal Reasons status indicates the user requested a resource that cannot legally be provided, such as a web page censored by a government. The server should include details about the legal demand in the response body if possible, including which authority issued the demand. The status code number 451 is a reference to Ray Bradbury\'s novel "Fahrenheit 451".',
        class: '4xx',
        category: 'Client Error',
        spec: 'RFC 7725',
        useCase: 'Content blocked by copyright law in a specific country, or website blocked by government court order.',
    },

    // ─── 5xx Server Errors ────────────────────────────────────────────────────
    {
        code: 500,
        name: 'Internal Server Error',
        description: 'Generic error when an unexpected condition was encountered.',
        longDescription: 'The 500 Internal Server Error status indicates the server encountered an unexpected condition that prevented it from fulfilling the request. This is a generic catch-all error when no more specific message is suitable. It typically means there is a bug or unhandled exception in the application code. The server should log detailed error information while returning a generic message to the client to avoid leaking sensitive information.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 9110',
        useCase: 'An unhandled exception in application code (e.g., null pointer dereference, database error) triggers a 500 response.',
    },
    {
        code: 501,
        name: 'Not Implemented',
        description: 'Server does not recognize the request method or lacks ability to fulfil it.',
        longDescription: 'The 501 Not Implemented status indicates the server does not support the functionality required to fulfill the request. This is the appropriate response when the server does not recognize the request method and is not capable of supporting it for any resource. Unlike 405, the 501 response indicates the server doesn\'t know the method at all, rather than the method being unsupported for a specific resource.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 9110',
        useCase: 'Server receives a PATCH request but has not implemented support for the PATCH method at all.',
    },
    {
        code: 502,
        name: 'Bad Gateway',
        description: 'Server was acting as a gateway and received an invalid response from an upstream server.',
        longDescription: 'The 502 Bad Gateway status indicates the server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed while attempting to fulfill the request. This often occurs in reverse proxy setups when the upstream application server crashes, returns garbage, or is temporarily unavailable. It is distinct from 503 in that the server itself is up but an upstream dependency is failing.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 9110',
        useCase: 'Nginx reverse proxy returns 502 when the Node.js application server process is down or returning malformed responses.',
    },
    {
        code: 503,
        name: 'Service Unavailable',
        description: 'Server is not ready to handle the request due to maintenance or overload.',
        longDescription: 'The 503 Service Unavailable status indicates the server is currently unable to handle the request due to a temporary overload or scheduled maintenance, which will likely be alleviated after some delay. The server may send a Retry-After header suggesting when the client should retry. This is often used with load balancers when all backend instances are unhealthy or during rolling deployments.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 9110',
        useCase: 'Server returns 503 during a scheduled maintenance window with Retry-After header indicating when to retry.',
    },
    {
        code: 504,
        name: 'Gateway Timeout',
        description: 'Server was acting as a gateway and did not receive a timely response from upstream.',
        longDescription: 'The 504 Gateway Timeout status indicates the server, while acting as a gateway or proxy, did not receive a timely response from an upstream server or some other auxiliary server needed to complete the request. This typically means the upstream application is too slow to respond within the configured timeout. It differs from 502 in that the upstream server didn\'t respond at all (timeout) vs. responding with an error.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 9110',
        useCase: 'Load balancer returns 504 when the backend API takes longer than 30 seconds to process a complex database query.',
    },
    {
        code: 505,
        name: 'HTTP Version Not Supported',
        description: 'Server does not support the HTTP protocol version used in the request.',
        longDescription: 'The 505 HTTP Version Not Supported status indicates the server does not support, or refuses to support, the major version of HTTP that was used in the request. The server should generate a representation for the 505 response that describes why that version is not supported and what other protocols are supported by that server. Rarely encountered in modern deployments as most servers support HTTP/1.1, HTTP/2, and HTTP/3.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 9110',
        useCase: 'A very old server receives an HTTP/2 request and returns 505 since it only supports HTTP/1.0.',
    },
    {
        code: 506,
        name: 'Variant Also Negotiates',
        description: 'Server has an internal configuration error in content negotiation.',
        longDescription: 'The 506 Variant Also Negotiates status (experimental) indicates the server has an internal configuration error: the chosen variant resource is configured to engage in transparent content negotiation itself, and is therefore not a proper end point in the negotiation process. This prevents an infinite negotiation loop. It is rarely encountered in practice and indicates a misconfigured server.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 2295',
        useCase: 'Server misconfiguration where a variant resource is itself configured as a negotiable resource, creating a circular reference.',
    },
    {
        code: 507,
        name: 'Insufficient Storage',
        description: 'Server is unable to store the representation needed to complete the request.',
        longDescription: 'The 507 Insufficient Storage status (WebDAV) indicates the method could not be performed on the resource because the server is unable to store the representation needed to successfully complete the request. This is a temporary condition — the server may have enough space at other times. It is distinct from a disk quota exceeded error, which would be a permanent condition for that user.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 4918 (WebDAV)',
        useCase: 'WebDAV PUT request fails because the server has run out of disk space to store the uploaded file.',
    },
    {
        code: 508,
        name: 'Loop Detected',
        description: 'Server detected an infinite loop while processing the request.',
        longDescription: 'The 508 Loop Detected status (WebDAV) indicates the server terminated an operation because it encountered an infinite loop while processing a request with "Depth: infinity". This can occur in WebDAV operations on collections when there are circular references between resources. The entire operation failed and no partial results are returned.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 5842 (WebDAV)',
        useCase: 'WebDAV COPY operation on a collection discovers a circular reference between directories and terminates with 508.',
    },
    {
        code: 510,
        name: 'Not Extended',
        description: 'Further extensions to the request are required for the server to fulfil it.',
        longDescription: 'The 510 Not Extended status (experimental) indicates that further extensions to the request are required for the server to fulfill it. The server should include information about the required extensions in the response body so the client knows what to add to make the request acceptable. This is part of the HTTP Extension Framework (RFC 2774) and is rarely used in practice.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 2774',
        useCase: 'Server requires a specific HTTP extension protocol header that the client did not include in the request.',
    },
    {
        code: 511,
        name: 'Network Authentication Required',
        description: 'Client needs to authenticate to gain network access.',
        longDescription: 'The 511 Network Authentication Required status indicates the client needs to authenticate to gain network access. This is intended for use by intercepting proxies used to control access to the network (e.g., "captive portals" used to require agreement to terms of service before granting full internet access). It is not intended for use by origin servers, but by network access infrastructure.',
        class: '5xx',
        category: 'Server Error',
        spec: 'RFC 6585',
        useCase: 'Hotel or airport Wi-Fi captive portal intercepts requests and returns 511 to redirect users to the login/terms page.',
    },
];
