import { FontPair, FontPairCategoryInfo } from './types';

export const FONT_PAIR_CATEGORIES: FontPairCategoryInfo[] = [
    { id: 'serif-sans', label: 'Serif + Sans' },
    { id: 'sans-sans', label: 'Sans + Sans' },
    { id: 'serif-serif', label: 'Serif + Serif' },
    { id: 'display-sans', label: 'Display + Sans' },
    { id: 'mono-sans', label: 'Mono + Sans' },
];

export const FONT_PAIRS: FontPair[] = [
    {
        id: '1',
        name: 'Classic Editorial',
        heading: 'Playfair Display',
        body: 'Source Sans 3',
        category: 'serif-sans',
        description: 'Elegant serif headlines with clean sans-serif body. Great for editorial, blogs, and magazines.',
    },
    {
        id: '2',
        name: 'Modern Professional',
        heading: 'Inter',
        body: 'Inter',
        category: 'sans-sans',
        description: 'Versatile and highly readable. Perfect for SaaS products, dashboards, and professional apps.',
    },
    {
        id: '3',
        name: 'Bold & Friendly',
        heading: 'Poppins',
        body: 'Open Sans',
        category: 'sans-sans',
        description: 'Geometric headings with a friendly body font. Ideal for startups and creative brands.',
    },
    {
        id: '4',
        name: 'Luxury Brand',
        heading: 'Cormorant Garamond',
        body: 'Montserrat',
        category: 'serif-sans',
        description: 'High-contrast serif with geometric sans. Perfect for luxury, fashion, and premium brands.',
    },
    {
        id: '5',
        name: 'Tech Forward',
        heading: 'Space Grotesk',
        body: 'DM Sans',
        category: 'sans-sans',
        description: 'Contemporary and techy. Great for developer tools, tech companies, and innovative products.',
    },
    {
        id: '6',
        name: 'Elegant Minimal',
        heading: 'Lora',
        body: 'Nunito Sans',
        category: 'serif-sans',
        description: 'Well-balanced and versatile. Suitable for portfolios, creative agencies, and lifestyle brands.',
    },
    {
        id: '7',
        name: 'Creative Agency',
        heading: 'Sora',
        body: 'Inter',
        category: 'sans-sans',
        description: 'Modern geometric headings with neutral body text. Ideal for agencies and design studios.',
    },
    {
        id: '8',
        name: 'Academic Formal',
        heading: 'Merriweather',
        body: 'Roboto',
        category: 'serif-sans',
        description: 'Traditional serif headings with clean body text. Great for academic, legal, and formal content.',
    },
    {
        id: '9',
        name: 'Developer Docs',
        heading: 'JetBrains Mono',
        body: 'Inter',
        category: 'mono-sans',
        description: 'Monospace headings for technical feel with clean body. Perfect for documentation and dev tools.',
    },
    {
        id: '10',
        name: 'Playful Display',
        heading: 'Outfit',
        body: 'Work Sans',
        category: 'display-sans',
        description: 'Fun and approachable headings with a balanced body. Great for creative projects and portfolios.',
    },
    {
        id: '11',
        name: 'News & Media',
        heading: 'Libre Baskerville',
        body: 'Source Sans 3',
        category: 'serif-sans',
        description: 'Authoritative serif headings with readable body. Ideal for news, media, and publishing.',
    },
    {
        id: '12',
        name: 'Startup Vibe',
        heading: 'Plus Jakarta Sans',
        body: 'DM Sans',
        category: 'sans-sans',
        description: 'Fresh and modern pairing. Perfect for tech startups, landing pages, and product sites.',
    },
    {
        id: '13',
        name: 'Vintage Charm',
        heading: 'DM Serif Display',
        body: 'DM Sans',
        category: 'serif-sans',
        description: 'A cohesive DM family pairing. Excellent for branding, restaurants, and artisan brands.',
    },
    {
        id: '14',
        name: 'Geometric Clean',
        heading: 'Manrope',
        body: 'Nunito Sans',
        category: 'sans-sans',
        description: 'Clean geometric pairing with great readability. Suitable for apps, dashboards, and tools.',
    },
    {
        id: '15',
        name: 'Literary Classic',
        heading: 'EB Garamond',
        body: 'Lato',
        category: 'serif-sans',
        description: 'Timeless serif with a neutral sans-serif body. Great for books, blogs, and literary sites.',
    },
    {
        id: '16',
        name: 'Code & Content',
        heading: 'Fira Code',
        body: 'Nunito Sans',
        category: 'mono-sans',
        description: 'Technical monospace with friendly body text. Great for developer blogs and coding tutorials.',
    },
    {
        id: '17',
        name: 'Elegant Serif Duo',
        heading: 'Playfair Display',
        body: 'Lora',
        category: 'serif-serif',
        description: 'All-serif pairing with contrast. Beautiful for luxury editorials and premium content.',
    },
    {
        id: '18',
        name: 'Bold Statement',
        heading: 'Archivo Black',
        body: 'Roboto',
        category: 'display-sans',
        description: 'Heavy impact headings with clean body. Perfect for bold branding and marketing pages.',
    },
];

export const PREVIEW_TEXT = {
    heading: 'The Quick Brown Fox Jumps Over The Lazy Dog',
    subheading: 'Discover the art of typography with perfect font pairings',
    body: 'Typography is one of the most important elements of design. The right font pairing can elevate your project from amateur to professional. A good combination creates visual harmony, establishes hierarchy, and improves readability across all devices.',
    short: 'A good font pairing creates visual harmony and establishes hierarchy.',
};

export const GOOGLE_FONTS_CSS_BASE = 'https://fonts.googleapis.com/css2';
