import { UnitCategoryData } from './types';

export const UNIT_CATEGORIES: UnitCategoryData[] = [
    {
        id: 'length',
        name: 'Length',
        icon: 'Ruler',
        baseUnit: 'm',
        units: [
            { id: 'm', name: 'Meter', symbol: 'm', toBase: 1 },
            { id: 'km', name: 'Kilometer', symbol: 'km', toBase: 1000 },
            { id: 'cm', name: 'Centimeter', symbol: 'cm', toBase: 0.01 },
            { id: 'mm', name: 'Millimeter', symbol: 'mm', toBase: 0.001 },
            { id: 'um', name: 'Micrometer', symbol: 'μm', toBase: 0.000001 },
            { id: 'nm', name: 'Nanometer', symbol: 'nm', toBase: 0.000000001 },
            { id: 'mi', name: 'Mile', symbol: 'mi', toBase: 1609.344 },
            { id: 'yd', name: 'Yard', symbol: 'yd', toBase: 0.9144 },
            { id: 'ft', name: 'Foot', symbol: 'ft', toBase: 0.3048 },
            { id: 'in', name: 'Inch', symbol: 'in', toBase: 0.0254 },
            { id: 'nmi', name: 'Nautical Mile', symbol: 'nmi', toBase: 1852 },
        ],
    },
    {
        id: 'weight',
        name: 'Weight/Mass',
        icon: 'Weight',
        baseUnit: 'kg',
        units: [
            { id: 'kg', name: 'Kilogram', symbol: 'kg', toBase: 1 },
            { id: 'g', name: 'Gram', symbol: 'g', toBase: 0.001 },
            { id: 'mg', name: 'Milligram', symbol: 'mg', toBase: 0.000001 },
            { id: 't', name: 'Metric Ton', symbol: 't', toBase: 1000 },
            { id: 'lb', name: 'Pound', symbol: 'lb', toBase: 0.45359237 },
            { id: 'oz', name: 'Ounce', symbol: 'oz', toBase: 0.02834952 },
            { id: 'st', name: 'Stone', symbol: 'st', toBase: 6.35029318 },
            { id: 'us_ton', name: 'US Ton', symbol: 'ton', toBase: 907.18474 },
            { id: 'imp_ton', name: 'Imperial Ton', symbol: 'long ton', toBase: 1016.0469088 },
        ],
    },
    {
        id: 'temperature',
        name: 'Temperature',
        icon: 'Thermometer',
        baseUnit: 'c',
        units: [
            {
                id: 'c',
                name: 'Celsius',
                symbol: '°C',
                toBase: 1,
                toBaseFn: (v) => v,
                fromBase: (v) => v,
            },
            {
                id: 'f',
                name: 'Fahrenheit',
                symbol: '°F',
                toBase: 1,
                toBaseFn: (v) => ((v - 32) * 5) / 9,
                fromBase: (v) => (v * 9) / 5 + 32,
            },
            {
                id: 'k',
                name: 'Kelvin',
                symbol: 'K',
                toBase: 1,
                toBaseFn: (v) => v - 273.15,
                fromBase: (v) => v + 273.15,
            },
            {
                id: 'r',
                name: 'Rankine',
                symbol: '°R',
                toBase: 1,
                toBaseFn: (v) => ((v - 491.67) * 5) / 9,
                fromBase: (v) => (v * 9) / 5 + 491.67,
            },
        ],
    },
    {
        id: 'volume',
        name: 'Volume',
        icon: 'Droplet',
        baseUnit: 'l',
        units: [
            { id: 'l', name: 'Liter', symbol: 'L', toBase: 1 },
            { id: 'ml', name: 'Milliliter', symbol: 'mL', toBase: 0.001 },
            { id: 'gal_us', name: 'Gallon (US)', symbol: 'gal', toBase: 3.78541 },
            { id: 'gal_imp', name: 'Gallon (Imperial)', symbol: 'gal (imp)', toBase: 4.54609 },
            { id: 'qt', name: 'Quart', symbol: 'qt', toBase: 0.946353 },
            { id: 'pt', name: 'Pint', symbol: 'pt', toBase: 0.473176 },
            { id: 'cup', name: 'Cup', symbol: 'cup', toBase: 0.236588 },
            { id: 'fl_oz', name: 'Fluid Ounce', symbol: 'fl oz', toBase: 0.0295735 },
            { id: 'tbsp', name: 'Tablespoon', symbol: 'tbsp', toBase: 0.0147868 },
            { id: 'tsp', name: 'Teaspoon', symbol: 'tsp', toBase: 0.00492892 },
            { id: 'm3', name: 'Cubic Meter', symbol: 'm³', toBase: 1000 },
            { id: 'cm3', name: 'Cubic Centimeter', symbol: 'cm³', toBase: 0.001 },
            { id: 'ft3', name: 'Cubic Foot', symbol: 'ft³', toBase: 28.3168 },
        ],
    },
    {
        id: 'area',
        name: 'Area',
        icon: 'Square',
        baseUnit: 'm2',
        units: [
            { id: 'm2', name: 'Square Meter', symbol: 'm²', toBase: 1 },
            { id: 'km2', name: 'Square Kilometer', symbol: 'km²', toBase: 1000000 },
            { id: 'ha', name: 'Hectare', symbol: 'ha', toBase: 10000 },
            { id: 'ac', name: 'Acre', symbol: 'ac', toBase: 4046.86 },
            { id: 'mi2', name: 'Square Mile', symbol: 'mi²', toBase: 2589988 },
            { id: 'yd2', name: 'Square Yard', symbol: 'yd²', toBase: 0.836127 },
            { id: 'ft2', name: 'Square Foot', symbol: 'ft²', toBase: 0.092903 },
            { id: 'in2', name: 'Square Inch', symbol: 'in²', toBase: 0.00064516 },
        ],
    },
    {
        id: 'speed',
        name: 'Speed',
        icon: 'Gauge',
        baseUnit: 'mps',
        units: [
            { id: 'mps', name: 'Meter per Second', symbol: 'm/s', toBase: 1 },
            { id: 'kph', name: 'Kilometer per Hour', symbol: 'km/h', toBase: 0.277778 },
            { id: 'mph', name: 'Miles per Hour', symbol: 'mph', toBase: 0.44704 },
            { id: 'kn', name: 'Knot', symbol: 'kn', toBase: 0.514444 },
            { id: 'mach', name: 'Mach', symbol: 'Ma', toBase: 343 },
            { id: 'fps', name: 'Foot per Second', symbol: 'ft/s', toBase: 0.3048 },
        ],
    },
    {
        id: 'pressure',
        name: 'Pressure',
        icon: 'ArrowDown',
        baseUnit: 'pa',
        units: [
            { id: 'pa', name: 'Pascal', symbol: 'Pa', toBase: 1 },
            { id: 'kpa', name: 'Kilopascal', symbol: 'kPa', toBase: 1000 },
            { id: 'mpa', name: 'Megapascal', symbol: 'MPa', toBase: 1000000 },
            { id: 'bar', name: 'Bar', symbol: 'bar', toBase: 100000 },
            { id: 'mbar', name: 'Millibar', symbol: 'mbar', toBase: 100 },
            { id: 'psi', name: 'PSI', symbol: 'psi', toBase: 6894.76 },
            { id: 'atm', name: 'Atmosphere', symbol: 'atm', toBase: 101325 },
            { id: 'torr', name: 'Torr', symbol: 'Torr', toBase: 133.322 },
            { id: 'mmhg', name: 'mmHg', symbol: 'mmHg', toBase: 133.322 },
        ],
    },
    {
        id: 'energy',
        name: 'Energy',
        icon: 'Zap',
        baseUnit: 'j',
        units: [
            { id: 'j', name: 'Joule', symbol: 'J', toBase: 1 },
            { id: 'kj', name: 'Kilojoule', symbol: 'kJ', toBase: 1000 },
            { id: 'cal', name: 'Calorie', symbol: 'cal', toBase: 4.184 },
            { id: 'kcal', name: 'Kilocalorie', symbol: 'kcal', toBase: 4184 },
            { id: 'wh', name: 'Watt-hour', symbol: 'Wh', toBase: 3600 },
            { id: 'kwh', name: 'Kilowatt-hour', symbol: 'kWh', toBase: 3600000 },
            { id: 'btu', name: 'BTU', symbol: 'BTU', toBase: 1055.06 },
            { id: 'ev', name: 'Electronvolt', symbol: 'eV', toBase: 1.602176634e-19 },
        ],
    },
    {
        id: 'power',
        name: 'Power',
        icon: 'Battery',
        baseUnit: 'w',
        units: [
            { id: 'w', name: 'Watt', symbol: 'W', toBase: 1 },
            { id: 'kw', name: 'Kilowatt', symbol: 'kW', toBase: 1000 },
            { id: 'mw', name: 'Megawatt', symbol: 'MW', toBase: 1000000 },
            { id: 'hp', name: 'Horsepower', symbol: 'hp', toBase: 745.7 },
            { id: 'hp_imp', name: 'Imperial HP', symbol: 'hp (imp)', toBase: 745.7 },
            { id: 'btu_hr', name: 'BTU/hr', symbol: 'BTU/hr', toBase: 0.293071 },
            { id: 'ton_ref', name: 'Ton Refrigeration', symbol: 'TR', toBase: 3516.85 },
        ],
    },
    {
        id: 'data',
        name: 'Data/Digital',
        icon: 'HardDrive',
        baseUnit: 'b',
        units: [
            { id: 'b', name: 'Byte', symbol: 'B', toBase: 1 },
            { id: 'bit', name: 'Bit', symbol: 'bit', toBase: 0.125 },
            { id: 'kb', name: 'Kilobyte', symbol: 'KB', toBase: 1024 },
            { id: 'mb', name: 'Megabyte', symbol: 'MB', toBase: 1048576 },
            { id: 'gb', name: 'Gigabyte', symbol: 'GB', toBase: 1073741824 },
            { id: 'tb', name: 'Terabyte', symbol: 'TB', toBase: 1099511627776 },
            { id: 'pb', name: 'Petabyte', symbol: 'PB', toBase: 1125899906842624 },
            { id: 'kib', name: 'Kibibyte', symbol: 'KiB', toBase: 1024 },
            { id: 'mib', name: 'Mebibyte', symbol: 'MiB', toBase: 1048576 },
            { id: 'gib', name: 'Gibibyte', symbol: 'GiB', toBase: 1073741824 },
            { id: 'tib', name: 'Tebibyte', symbol: 'TiB', toBase: 1099511627776 },
        ],
    },
    {
        id: 'time',
        name: 'Time',
        icon: 'Clock',
        baseUnit: 's',
        units: [
            { id: 's', name: 'Second', symbol: 's', toBase: 1 },
            { id: 'ms', name: 'Millisecond', symbol: 'ms', toBase: 0.001 },
            { id: 'us', name: 'Microsecond', symbol: 'μs', toBase: 0.000001 },
            { id: 'ns', name: 'Nanosecond', symbol: 'ns', toBase: 0.000000001 },
            { id: 'min', name: 'Minute', symbol: 'min', toBase: 60 },
            { id: 'h', name: 'Hour', symbol: 'h', toBase: 3600 },
            { id: 'd', name: 'Day', symbol: 'd', toBase: 86400 },
            { id: 'wk', name: 'Week', symbol: 'wk', toBase: 604800 },
            { id: 'mo', name: 'Month (avg)', symbol: 'mo', toBase: 2629746 },
            { id: 'y', name: 'Year', symbol: 'y', toBase: 31556952 },
            { id: 'dec', name: 'Decade', symbol: 'dec', toBase: 315569520 },
            { id: 'cen', name: 'Century', symbol: 'cen', toBase: 3155695200 },
        ],
    },
];

export const CATEGORY_ICONS: Record<
    string,
    { icon: string; color: string; bgColor: string }
> = {
    length: { icon: 'Ruler', color: 'text-blue-600', bgColor: 'bg-blue-50' },
    weight: { icon: 'Weight', color: 'text-amber-600', bgColor: 'bg-amber-50' },
    temperature: { icon: 'Thermometer', color: 'text-red-600', bgColor: 'bg-red-50' },
    volume: { icon: 'Droplet', color: 'text-cyan-600', bgColor: 'bg-cyan-50' },
    area: { icon: 'Square', color: 'text-emerald-600', bgColor: 'bg-emerald-50' },
    speed: { icon: 'Gauge', color: 'text-violet-600', bgColor: 'bg-violet-50' },
    pressure: { icon: 'ArrowDown', color: 'text-slate-600', bgColor: 'bg-slate-50' },
    energy: { icon: 'Zap', color: 'text-yellow-600', bgColor: 'bg-yellow-50' },
    power: { icon: 'Battery', color: 'text-green-600', bgColor: 'bg-green-50' },
    data: { icon: 'HardDrive', color: 'text-indigo-600', bgColor: 'bg-indigo-50' },
    time: { icon: 'Clock', color: 'text-gray-600', bgColor: 'bg-gray-50' },
};
