import {
    CheckCircle2,
    XCircle,
    FileClock,
    ShieldAlert,
    BadgeCheck,
    Calendar,
    ListChecks,
    FileEdit,
    Banknote
} from 'lucide-react';
import { StampTemplate } from './types';

export const MAX_PDF_SIZE = 20 * 1024 * 1024; // 20MB
export const PDF_PREVIEW_SCALE = 1.5;

export const DEFAULT_STAMP_WIDTH = 220;
export const DEFAULT_STAMP_HEIGHT = 100;

export const STAMP_COLORS = {
    green: { color: '#16a34a', bg: '#f0fdf4', border: '#86efac' },
    red: { color: '#dc2626', bg: '#fef2f2', border: '#fca5a5' },
    blue: { color: '#2563eb', bg: '#eff6ff', border: '#93c5fd' },
    amber: { color: '#d97706', bg: '#fffbeb', border: '#fcd34d' },
    gray: { color: '#4b5563', bg: '#f9fafb', border: '#d1d5db' },
    purple: { color: '#7c3aed', bg: '#f5f3ff', border: '#c4b5fd' },
};

export const STAMP_TEMPLATES: StampTemplate[] = [
    {
        id: 'approved',
        name: 'Approved',
        type: 'approval',
        icon: CheckCircle2,
        defaultConfig: {
            label: 'APPROVED',
            status: 'approved',
            color: STAMP_COLORS.green.color,
            backgroundColor: STAMP_COLORS.green.bg,
            borderColor: STAMP_COLORS.green.border,
            width: 220,
            height: 90,
            fontSize: 14,
            opacity: 1,
            rotation: 0,
        },
    },
    {
        id: 'rejected',
        name: 'Rejected',
        type: 'approval',
        icon: XCircle,
        defaultConfig: {
            label: 'REJECTED',
            status: 'rejected',
            color: STAMP_COLORS.red.color,
            backgroundColor: STAMP_COLORS.red.bg,
            borderColor: STAMP_COLORS.red.border,
            width: 220,
            height: 90,
            fontSize: 14,
            opacity: 1,
            rotation: 0,
        },
    },
    {
        id: 'draft',
        name: 'Draft',
        type: 'approval',
        icon: FileClock,
        defaultConfig: {
            label: 'DRAFT',
            status: 'draft',
            color: STAMP_COLORS.amber.color,
            backgroundColor: STAMP_COLORS.amber.bg,
            borderColor: STAMP_COLORS.amber.border,
            width: 200,
            height: 80,
            fontSize: 14,
            opacity: 1,
            rotation: 0,
        },
    },
    {
        id: 'confidential',
        name: 'Confidential',
        type: 'approval',
        icon: ShieldAlert,
        defaultConfig: {
            label: 'CONFIDENTIAL',
            status: 'confidential',
            color: STAMP_COLORS.purple.color,
            backgroundColor: STAMP_COLORS.purple.bg,
            borderColor: STAMP_COLORS.purple.border,
            width: 220,
            height: 80,
            fontSize: 14,
            opacity: 1,
            rotation: 0,
        },
    },
    {
        id: 'reviewed',
        name: 'Reviewed',
        type: 'approval',
        icon: BadgeCheck,
        defaultConfig: {
            label: 'REVIEWED',
            status: 'reviewed',
            color: STAMP_COLORS.blue.color,
            backgroundColor: STAMP_COLORS.blue.bg,
            borderColor: STAMP_COLORS.blue.border,
            width: 220,
            height: 90,
            fontSize: 14,
            opacity: 1,
            rotation: 0,
        },
    },
    {
        id: 'date',
        name: 'Date Stamp',
        type: 'date',
        icon: Calendar,
        defaultConfig: {
            dateLabel: 'Date',
            date: new Date().toISOString().split('T')[0],
            color: STAMP_COLORS.gray.color,
            backgroundColor: STAMP_COLORS.gray.bg,
            borderColor: STAMP_COLORS.gray.border,
            width: 200,
            height: 70,
            fontSize: 13,
            opacity: 1,
            rotation: 0,
        },
    },
    {
        id: 'checklist',
        name: 'Checklist',
        type: 'checklist',
        icon: ListChecks,
        defaultConfig: {
            checklistTitle: 'Checklist',
            checklist: [
                { id: '1', text: 'Item 1', checked: false },
                { id: '2', text: 'Item 2', checked: false },
                { id: '3', text: 'Item 3', checked: false },
            ],
            color: STAMP_COLORS.blue.color,
            backgroundColor: STAMP_COLORS.blue.bg,
            borderColor: STAMP_COLORS.blue.border,
            width: 240,
            height: 140,
            fontSize: 12,
            opacity: 1,
            rotation: 0,
        },
    },
    {
        id: 'notes',
        name: 'Notes',
        type: 'notes',
        icon: FileEdit,
        defaultConfig: {
            notes: '',
            color: STAMP_COLORS.amber.color,
            backgroundColor: STAMP_COLORS.amber.bg,
            borderColor: STAMP_COLORS.amber.border,
            width: 240,
            height: 120,
            fontSize: 12,
            opacity: 1,
            rotation: 0,
        },
    },
    {
        id: 'cost',
        name: 'Cost / Fee',
        type: 'cost',
        icon: Banknote,
        defaultConfig: {
            costLabel: 'Total',
            costAmount: '0',
            costCurrency: 'IDR',
            color: STAMP_COLORS.green.color,
            backgroundColor: STAMP_COLORS.green.bg,
            borderColor: STAMP_COLORS.green.border,
            width: 220,
            height: 80,
            fontSize: 13,
            opacity: 1,
            rotation: 0,
        },
    },
];

