import type { ComponentType } from 'react';
import {
  Archive,
  ArrowsLeftRight,
  ArrowsOut,
  Barcode,
  BracketsCurly,
  Calculator,
  Calendar,
  CalendarDots,
  ChartLineUp,
  CircleHalf,
  Clock,
  CodeSimple,
  Coins,
  Cpu,
  Crop,
  Cube,
  CurrencyDollar,
  Cursor,
  Eye,
  FileArrowDown,
  FileCode,
  FileImage,
  FilePlus,
  FileText,
  FilmStrip,
  FunnelSimple,
  GitMerge,
  Globe,
  GraduationCap,
  GridFour,
  HardDrives,
  Hash,
  Images,
  Key,
  KeyReturn,
  Link,
  LinkSimple,
  Lock,
  LockKey,
  MagicWand,
  MapTrifold,
  Microphone,
  NotePencil,
  PaintBrush,
  Palette,
  Percent,
  QrCode,
  Question,
  Receipt,
  Robot,
  Ruler,
  Scan,
  ShareNetwork,
  Shield,
  SpeakerHigh,
  SplitHorizontal,
  Square,
  Stack,
  Terminal,
  TextT,
  Timer,
  TrendUp,
  Triangle,
  WifiHigh,
  XLogo
} from '@phosphor-icons/react/dist/ssr';
import type { IconProps } from '@phosphor-icons/react';

const icons: Record<string, ComponentType<IconProps>> = {
  Archive: Archive,
  ArrowsLeftRight: ArrowsLeftRight,
  ArrowsOut: ArrowsOut,
  Barcode: Barcode,
  BracketsCurly: BracketsCurly,
  Calculator: Calculator,
  Calendar: Calendar,
  CalendarDots: CalendarDots,
  ChartLineUp: ChartLineUp,
  CircleHalf: CircleHalf,
  Clock: Clock,
  CodeSimple: CodeSimple,
  Coins: Coins,
  Cpu: Cpu,
  Crop: Crop,
  Cube: Cube,
  CurrencyDollar: CurrencyDollar,
  Cursor: Cursor,
  Eye: Eye,
  FileArrowDown: FileArrowDown,
  FileCode: FileCode,
  FileImage: FileImage,
  FilePlus: FilePlus,
  FileText: FileText,
  FilmStrip: FilmStrip,
  FunnelSimple: FunnelSimple,
  GitMerge: GitMerge,
  Globe: Globe,
  GraduationCap: GraduationCap,
  GridFour: GridFour,
  HardDrives: HardDrives,
  Hash: Hash,
  Images: Images,
  Key: Key,
  KeyReturn: KeyReturn,
  Link: Link,
  LinkSimple: LinkSimple,
  Lock: Lock,
  LockKey: LockKey,
  MagicWand: MagicWand,
  MapTrifold: MapTrifold,
  Microphone: Microphone,
  NotePencil: NotePencil,
  PaintBrush: PaintBrush,
  Palette: Palette,
  Percent: Percent,
  QrCode: QrCode,
  Question: Question,
  Receipt: Receipt,
  Robot: Robot,
  Ruler: Ruler,
  Scan: Scan,
  ShareNetwork: ShareNetwork,
  Shield: Shield,
  SpeakerHigh: SpeakerHigh,
  SplitHorizontal: SplitHorizontal,
  Square: Square,
  Stack: Stack,
  Terminal: Terminal,
  TextT: TextT,
  Timer: Timer,
  TrendUp: TrendUp,
  Triangle: Triangle,
  WifiHigh: WifiHigh,
  XLogo: XLogo
};

export type IconName = keyof typeof icons;

interface IconRendererProps extends IconProps {
  name: IconName;
}

export function IconRenderer({ name, ...props }: IconRendererProps) {
  const IconComponent = icons[name];
  if (!IconComponent) {
    // Fallback icon
    return <Question weight="duotone" {...props} />;
  }
  return <IconComponent weight="duotone" {...props} />;
}
